import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col ">
        <header className="bg-white relative w-full">{/* <Navbar /> */}</header>
        <main className=" grow">{children}</main>

        <footer className="flex border-t justify-center items-center text-[13px] py-3">
          <div className="flex before:max-w-7xl h-14 items-center">
            <div>Hak Cipta &#9400; 2024 Hadar Karya Utama</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
